name: Publish on GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Clone Github Repo Action
        uses: GuillaumeFalourd/clone-github-repo-action@v2
        
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.2.0
        
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -r requirements.txt
      
      - name: Build html
        run: |
          make html
          rm -r build/html/_sources
      
      - name: Publish on GitHub Pages
        uses: ftnext/action-push-ghpages@v1.0.0-alpha
        with:
          build_dir: build/html
          github_token: ${{ secrets.GITHUB_TOKEN }}
