- name: clone-repository
  uses: GuillaumeFalourd/clone-github-repo-action@v2
  with:
    owner: 'GuillaumeFalourd'
    repository: 'poc-github-actions'

- name: Run-Install-Library-Action 
  on: 
  push:
    branches: 
      - master 
  jobs:
  build-and-deploy: 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Install WHL to the cluster
      uses: Herman-Wu/databrick-install-lib-action@master
      with:
        databrick-server-uri: 'https://XXXX.XX.azuredatabricks.net'
        databrick-token: ' <databrick-token> '
        databrick-cluster-id: ' < databrick-cluster-id >'
        databrick-libraries: ' XXXX.whl  YYYY.whl ZZZ.whl'
        databrick-dbfs-path: 'dbfs:/mnt/XXXX/ '
        
- name: Build-LaTeX-document
  on: [push]
  jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: dante-ev/latex-action@latest
        with:
          root_file: main.tex
    
    
- name: Push-to-Github-pages
  on: [push]
  jobs:
    Explore-GitHub-Actions:
      runs-on: ubuntu-latest
      steps:
    
    
